version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY=:0
    command: ./proj/cmake/build/Debug/FirstDraw/FirstDraw
